# Permalinks
permalink:           pretty


pygments:         true

# Setup
title:               Blog.hwdong.com
tagline:             'Research, Teaching, Blogging'
url:                 http://blog.hwdong.com
paginate:            4
baseurl:             ""
excerpt_separator: <!--more-->

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Hongwei Dong
  url:               https://hwdong.com
  email:             hwdong.cn@gmail.com

# Custom vars
version:             3.0.0
github:
  repo:              https://hwdong.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
