# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            blog.hwdong.com
tagline:          'The blog of Hongwei Dong'
description:      'A reserved <a href="http://hwdong.com" target="_blank">hwdong.com</a> The blog is based on the theme <a href = "http://lanyon.getpoole.com">lanyon </a>.Contacted me by <a href="http://hwdong.com" target="_blank">hwdong.com</a>.'
url:              http://hwdong.com

author:
  name:           'Hongwei Dong'
  url:            http://hwdong.com

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/hwdong
    
pages_list:       
  About: '/about'
  Archive: '/archive'
  Research: 'research'
  Teaching: 'teaching'
  Blog: 'http://hwdong.wordpress.com'
  
